version: "3.7"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # # copy the sql script to create tables
      - ./src/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # # Copy the sql script to create views
      - ./src/sql/create_views.sql:/docker-entrypoint-initdb.d/create_views.sql
      # # copy the sql script to fill tables
      # - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
