version: "3.7"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    volumes:
      # Dev storage of postgres data
      - ./postgres-data:/var/lib/postgresql/data
      # Copy the sql script to create tables
      - ./src/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # Copy the sql script to create views
      - ./src/sql/create_views.sql:/docker-entrypoint-initdb.d/create_views.sql
      # # Copy the sql script to fill tables
      # - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
